databases:
  db1:
    dsn: mssql+pyodbc://Username:Password@ServerAddress:1433/DatabaseName?driver=ODBC Driver 17 for SQL Server
    autocommit: false
metrics:
  orderCount:
    type: counter
    description: Order Status Book Requests
    labels: [bookState, moduleType]
    # expiration: 24h
    # states: [New,ReserveFailed,Reserved,IssueFailed,Issued]

queries:
  query1:
    interval: 10
    #  schedule: "*/5 * * * *"
    databases: [db1]
    timeout: 2
    metrics: [orderCount]
    sql: |
     select 
       bs.Title                       as bookState,
       mt.Title                       as moduleType,
       ABS(CHECKSUM(NewId())) % 14    as orderCount
     from dbo.BookState as bs
     cross join dbo.ModuleType as mt with(nolock)
     